config/routes.rb
Rails.application.routes.draw do
    
  resources :applications    

  get 'welcome/index'

  get 'welcome/about'

  root 'welcome#index'
    
end

app/models/application.rb
class Application < ApplicationRecord
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  def index
      @applications = Application.all
  end

  def show
      @application = Application.find(params[:id])
  end

  def new
      @application = Application.new
  end

   def create

     @application = Application.new
     @application.appname = params[:application][:appname]
     @application.url = params[:application][:url]

     if @application.save
       flash[:notice] = "Application was registered."
       redirect_to @application
     else
       flash.now[:alert] = "There was an error saving the application. Please try again."
       render :new
     end
   end    
    
  def edit
      @application = Application.find(params[:id])
  end
    
   def update
     @application = Application.find(params[:id])
     @application.appname = params[:application][:appname]
     @application.url = params[:application][:url]
 
     if @application.save
       flash[:notice] = "Application was updated."
       redirect_to @application
     else
       flash.now[:alert] = "There was an error saving the application. Please try again."
       render :edit
     end
   end 
    
   def destroy
     @application = Application.find(params[:id])
 
     if @application.destroy
       flash[:notice] = "\"#{@application.appname}\" was deleted successfully."
       redirect_to applications_path
     else
       flash.now[:alert] = "There was an error deleting the application."
       render :show
     end
   end
    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/applications/edit.html.erb
 <h1>Edit Application</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for applications</p>
     <ul>
       <li>Make sure it rhymes.</li>
       <li>Don't use the letter "A".</li>
       <li>The incessant use of hashtags will get you banned.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @application do |f| %>
       <div class="form-group">
         <%= f.label :appname %>
         <%= f.text_field :appname, class: 'form-control', placeholder: "Enter post title" %>
       </div>
       <div class="form-group">
         <%= f.label :url %>
         <%= f.text_area :url, class: 'form-control', placeholder: "Enter url." %>
       </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/applications/index.html.erb
 <h1>All Applications</h1>
 <% @applications.each do |application| %>
   <div class="media">
     <div class="media-body">
       <h4 class="media-heading">
         <%= link_to application.appname, application %>
       </h4>
     </div>
   </div>
 <% end %>

app/views/applications/new.html.erb
 <h1>New Post</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for posts</p>
     <ul>
       <li>Make sure it rhymes.</li>
       <li>Don't use the letter "A".</li>
       <li>The incessant use of hashtags will get you banned.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @application do |f| %>
       <div class="form-group">
         <%= f.label :appname %>
         <%= f.text_field :appname, class: 'form-control', placeholder: "Enter application name." %>
       </div>
       <div class="form-group">
         <%= f.label :url %>
         <%= f.text_area :url, class: 'form-control', placeholder: "Enter url application" %>
       </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/applications/show.html.erb
 <h1><%= @application.appname %></h1>
 
 <div class="row">
   <div class="col-md-8">
     <p><%= @application.url %></p>
   </div>
   <div class="col-md-4">
 <!-- #5 -->
     <%= link_to "Edit", edit_application_path(@application), class: 'btn btn-success' %>
     <%= link_to "Delete Application", @application, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this application?'} %>
   </div>
 </div>
   </div>
 </div>

app/views/layouts/application.html.erb
 <!DOCTYPE html>
 <html>
 <head>
   <title>BlocMetrics</title>
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <%= stylesheet_link_tag    "application", media: "all" %>
   <%= javascript_include_tag "application" %>
   <%= csrf_meta_tags %>
 </head>
 <body>
   <div class="container">
     <ul class="nav nav-tabs">
       <li><%= link_to "Bloccit", welcome_index_path %></li>
       <li><%= link_to "About", welcome_about_path %></li>
     </ul>

     <% if flash[:notice] %>
       <div class="alert alert-success">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:notice] %>
       </div>
     <% elsif flash[:alert] %>
       <div class="alert alert-warning">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:alert] %>
       </div>
     <% end %>       
       
     <%= yield %>
   </div>

 </body>
 </html>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>